FROM python:3.12-slim

WORKDIR /app

COPY model.pth
COPY backend/model.py
COPY backend/view.py
COPY requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "backend/view.py"]