FROM python:3.12-slim

WORKDIR /app

COPY model.pth /app/
COPY backend/model.py /app/backend/
COPY backend/view.py /app/backend/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "backend/view.py"]